version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 643625512126.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app 643625512126.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 643625512126.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
